apiVersion: v1
kind: Service
metadata:
  name: userprofileapi
  labels:
    application: scmuserprofile
    service: userprofileapi
spec:
  type: ClusterIP
  selector:
    application: scmuserprofile
    service: userprofileapi
  ports:
    - port: 80
      targetPort: 80
