  jobs:
    - job: Kubectl_ApplyConfig
      continueOnError: false
      steps:
      - task: Kubernetes@1
        displayName: 'kubectl apply using configFile'
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
          azureResourceGroup: ${{ parameters.azureResourceGroup }}
          kubernetesCluster: ${{ parameters.kubernetesCluster }}
          command: apply
          useConfigurationFile: true
          configuration: ${{ parameters.configurationPath }}