trigger:
- 'none'

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

pr: none

parameters:

  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Plan
    - Apply
    - Destroy

variables:
  - name: backendServiceArm
    value: 'aks-svc-con'
  - name: backendAzureRmResourceGroupName
    value: 'tfstate-dev-rg'
  - name: backendAzureRmStorageAccountName
    value: 'kktfstatedevstg'
  - name: backendAzureRmContainerName
    value: 'akstfstatefiles'
  - name: backendAzureRmKey
    value: 'terraform.tfstate'
  - name: environment
    value: 'dev'
  - name: terraform_version
    value: '1.1.2'
  - name: location
    value: 'westeurope'
  - name: aksAzureRmResourceGroupName
    value: 'kkdcd5-aks-rg'
  - name: aksName
    value: 'kkdcd5aksdev'
  - name: action
    value: ${{ parameters.Action }}

stages :   
  - stage: terraform_remotestate
    condition: ne('${{ parameters.Action }}', 'Destroy')
    jobs:
      - template: templates/remote-storage-az-cli.yaml
        parameters:
          backendServiceArm: ${{ variables.backendServiceArm }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
          backendAzureRmKey: ${{ variables.backendAzureRmKey }}
          location: ${{ variables.location }}

  - stage: terraform_validate
    condition: ne('${{ parameters.Action }}', 'Destroy')
    jobs:
      - template: templates/terraform-validate.yaml
        parameters:
          backendServiceArm: ${{ variables.backendServiceArm }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
          backendAzureRmKey: ${{ variables.backendAzureRmKey }}
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}

  - stage: terraform_plan
    dependsOn: [terraform_validate]
    condition: ne('${{ parameters.Action }}', 'Destroy')
    jobs:
      - template: templates/terraform-plan.yaml
        parameters:
          backendServiceArm: ${{ variables.backendServiceArm }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
          backendAzureRmKey: ${{ variables.backendAzureRmKey }}
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}

  - stage: terraform_apply
    dependsOn: [terraform_plan]
    condition: ne('${{ parameters.Action }}', 'Destroy')
    jobs:
      - template: templates/terraform-apply.yaml
        parameters:
          backendServiceArm: ${{ variables.backendServiceArm }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
          backendAzureRmKey: ${{ variables.backendAzureRmKey }}
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}

  # - stage: bootstrap
  #   dependsOn: [terraform_apply]
  #   condition: and(succeeded(), ne('${{ parameters.Action }}', 'Destroy'))
  #   jobs:
  #     - template: templates/aks-az-cli.yaml
  #       parameters:
  #         backendServiceArm: ${{ variables.backendServiceArm }}
  #         aksAzureRmResourceGroupName: ${{ variables.aksAzureRmResourceGroupName }}
  #         aksName: ${{ variables.aksName }}

  - stage: terraform_destroy
    condition: contains('${{ parameters.Action }}', 'Destroy')
    jobs:
      - template: templates/terraform-destroy.yaml
        parameters:
          backendServiceArm: ${{ variables.backendServiceArm }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
          backendAzureRmKey: ${{ variables.backendAzureRmKey }}
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}