version: '3'
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: ../../dockerfiles/poi
    image: tripinsights/poi:1.0

  trips:
    build:
      context: ../src/trips
      dockerfile: ../../dockerfiles/trips
    image: tripinsights/trips:1.0
  
  user-java:
    build:
      context: ../src/user-java
      dockerfile: ../../dockerfiles/userjava
    image: tripinsights/user-java:1.0
  
  userprofile:
    build:
      context: ../src/userprofile
      dockerfile: ../../dockerfiles/userprofile
    image: tripinsights/userprofile:1.0

  tripviewer:
    build:
      context: ../src/tripviewer
      dockerfile: ../../dockerfiles/tripviewer
    image: tripinsights/tripviewer:1.0